 node('maven-appdev') {
    GUID='e05e'
    CLUSTER='https://master.na39.openshift.opentlc.com'
    echo "GUID: ${GUID}"
    echo "CLUSTER: ${CLUSTER}"

    // Checkout Source Code.
    stage('Checkout Source') {
      git url: 'https://github.com/cfoskin/appvdev_homework.git'
    }

    echo "directory: "
    sh "pwd"
    sh "ls"

    dir("MLBParks") {
      def groupId    = getGroupIdFromPom("pom.xml")
      def artifactId = getArtifactIdFromPom("pom.xml")
      def version    = getVersionFromPom("pom.xml")
      // Set the tag for the development image: version + build number
      def devTag  = "${version}-${BUILD_NUMBER}"
      // Set the tag for the production image: version
      def prodTag = "${version}"
      echo " Dev TAG: ${devTag}"
      echo " Prod TAG: ${prodTag}"

      def mvnCmd = "mvn -s ./nexus_settings.xml"
      echo "mvnCmd: ${mvnCmd}"

      // Using Maven build the war file
      stage('Build war') {
        echo "Building version ${devTag}"
        sh "${mvnCmd} clean package -DskipTests"
      }

      // Using Maven run the unit tests
      stage('Unit Tests') {
        echo "Running Unit Tests"
        sh "${mvnCmd} test"
      }

      stage('Code Analysis') {
        echo "Running Code Analysis"
        sh "${mvnCmd} sonar:sonar -Dsonar.host.url=http://sonarqube-${GUID}-sonarqube.apps.na39.openshift.opentlc.com -Dsonar.projectName=${JOB_BASE_NAME}-${devTag}"
      }

      // Build the OpenShift Image in OpenShift and tag it.
      stage('Build and Tag OpenShift Image') {
        echo "Building OpenShift container image mlbparks:${devTag}"
        // Start Binary Build in OpenShift using the file we just published
        // The filename is openshift-tasks.war in the 'target' directory of your current
        // Jenkins workspace
        // Replace xyz-tasks-dev with the name of your dev project
        sh "oc start-build mlbparks --follow --from-file=./target/mlbparks.war -n $GUID-parks-dev"

        // OR use the file you just published into Nexus:
        // sh "oc start-build tasks --follow --from-file=http://nexus3.xyz-nexus.svc.cluster.local:8081/repository/releases/org/jboss/quickstarts/eap/tasks/${version}/tasks-${version}.war -n xyz-tasks-dev"
        // Tag the image using the devTag
        openshiftTag alias: 'false', destStream: 'mlbparks', destTag: devTag, destinationNamespace: 'e05e-parks-dev', namespace: 'e05e-parks-dev', srcStream: 'mlbparks', srcTag: 'latest', verbose: 'false'
      }

      stage('Publish to Nexus') {
        echo "Publish to Nexus"
        sh "${mvnCmd} deploy -DskipTests=true -DaltDeploymentRepository=nexus::default::http://nexus3-${GUID}-nexus.apps.na39.openshift.opentlc.com/repository/releases"
      }

            // Deploy the built image to the Development Environment.
      stage('Deploy to Dev') {
        echo "Deploying container image to Development Project"

        // Update the Image on the Development Deployment Config
        sh "oc set image dc/mlbparks mlbparks=docker-registry.default.svc:5000/${GUID}-parks-dev/mlbparks:${devTag} -n ${GUID}-parks-dev"

        // Update the Config Map which contains the users for the Tasks application
        // sh "oc delete configmap tasks-config -n ${GUID}-parks-dev --ignore-not-found=true"
        // sh "oc create configmap tasks-config --from-file=./configuration/application-users.properties --from-file=./configuration/application-roles.properties -n xyz-tasks-dev"

        // Deploy the development application.
        // Replace xyz-tasks-dev with the name of your production project
        openshiftDeploy depCfg: 'mlbparks', namespace: 'e05e-parks-dev', verbose: 'false', waitTime: '', waitUnit: 'sec'
        openshiftVerifyDeployment depCfg: 'mlbparks', namespace: 'e05e-parks-dev', replicaCount: '1', verbose: 'false', verifyReplicaCount: 'false', waitTime: '', waitUnit: 'sec'
        openshiftVerifyService namespace: 'e05e-parks-dev', svcName: 'mlbparks', verbose: 'false'
      }
      // Run Integration Tests in the Development Environment.
      stage('Integration Tests') {
        echo "Running Integration Tests"
        sleep 30

        //check health endpoint
        echo "Checking health endpoint"
        sh "curl -i -H 'Content-Length: 0' -X GET http://mlbparks.e05e-parks-dev.svc:8080/ws/healthz/"

        // checking info endpoint
        echo "Checking info endpoint"
        sh "curl -i -H 'Content-Length: 0' -X GET http://mlbparks.e05e-parks-dev.svc:8080/ws/info/"
      }

      // Copy Image to Nexus Docker Registry
      stage('Copy Image to Nexus Docker Registry') {
        echo "Copy image to Nexus Docker Registry"
        sh "skopeo copy --src-tls-verify=false --dest-tls-verify=false --src-creds openshift:\$(oc whoami -t) --dest-creds admin:admin123 docker://docker-registry.default.svc.cluster.local:5000/${GUID}-parks-dev/mlbparks:${devTag} docker://nexus-registry.${GUID}-nexus.svc.cluster.local:5000/mlbparks:${devTag}"

        // Tag the built image with the production tag.
        // Replace xyz-tasks-dev with the name of your dev project
        openshiftTag alias: 'false', destStream: 'mlbparks', destTag: prodTag, destinationNamespace: 'e05e-parks-dev', namespace: 'e05e-parks-dev', srcStream: 'mlbparks', srcTag: devTag, verbose: 'false'
      }

      // Blue/Green Deployment into Production
      // -------------------------------------
      // Do not activate the new version yet.
      def destApp   = "mlbparks-green"
      def activeApp = ""

      stage('Blue/Green Production Deployment') {
        // Replace xyz-tasks-dev and xyz-tasks-prod with
        // your project names
        activeApp = sh(returnStdout: true, script: "oc get route mlbparks -n ${GUID}-parks-prod -o jsonpath='{ .spec.to.name }'").trim()
        if (activeApp == "mlbparks-green") {
          destApp = "mlbparks-blue"
        }
        echo "Active Application:      " + activeApp
        echo "Destination Application: " + destApp

        // Update the Image on the Production Deployment Config
        sh "oc set image dc/${destApp} ${destApp}=docker-registry.default.svc:5000/${GUID}-parks-dev/mlbparks:${prodTag} -n ${GUID}-parks-prod"

        // Deploy the inactive application.
        // Replace xyz-tasks-prod with the name of your production project
        openshiftDeploy depCfg: destApp, namespace: 'e05e-parks-prod', verbose: 'false', waitTime: '', waitUnit: 'sec'
        openshiftVerifyDeployment depCfg: destApp, namespace: 'e05e-parks-prod', replicaCount: '1', verbose: 'false', verifyReplicaCount: 'true', waitTime: '', waitUnit: 'sec'
        openshiftVerifyService namespace: 'e05e-parks-prod', svcName: destApp, verbose: 'false'
      }

      stage('Switch over to new Version') {
        input "Switch Production?"

        echo "Switching Production application to ${destApp}."
        // Replace xyz-tasks-prod with the name of your production project
        sh 'oc patch route mlbparks -n ${GUID}-parks-prod -p \'{"spec":{"to":{"name":"' + destApp + '"}}}\''
      }

       }
  }

// Convenience Functions to read variables from the pom.xml. 
// Do not change anything below this line.
def getVersionFromPom(pom) {
  def matcher = readFile(pom) =~ '<version>(.+)</version>'
  matcher ? matcher[0][1] : null
}
def getGroupIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<groupId>(.+)</groupId>'
  matcher ? matcher[0][1] : null
}
def getArtifactIdFromPom(pom) {
  def matcher = readFile(pom) =~ '<artifactId>(.+)</artifactId>'
  matcher ? matcher[0][1] : null
}
